on:
  workflow_call

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4  # Clones the repository with Terraform config files

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialise
        run: terraform init
        
      - name: List files before zipping
        run: ls -la

      - name: Create zip file
        run: zip -r test.zip .terraform.lock.hcl test2.tf .terraform

      - name: List files after zipping
        run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test.zip
          path: test.zip
