name: checkov

on:
  workflow_call:

jobs:
  # This workflow contains a single job called "scan"
  scan:
    runs-on: ubuntu-latest
    steps:   
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test2.zip
        
      - name: List downloaded files
        run: ls -la 
        
      - run: terraform fmt test
    
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
